### ISSUE TITLE
Signing the DLL

### ISSUE THREAD

**Issue by Sicos1977** [RichardD2/NTFS-Streams#3]
Hi,

Could you sign the DLL? I did want to use it in a project with strong names (signed) and couldn't use the nuget package because it isn't. I ended up with compiling the source myself but It would be handy if I does not need to do that.

Greetings,
Kees

**Comment by RichardD2** [comment]
I've added a strong name and pushed the new assembly to NuGet. I've bumped the version up to 4.0, as changing the assembly identity is probably a breaking change.

**Comment by Sicos1977** [comment]
Signing is not a code breaking change... it would be if it was the other way around.
Thanks.
