### ISSUE TITLE
How to create an Alternative Stream ?

### ISSUE THREAD

**Issue by mridah** [RichardD2/NTFS-Streams#6]
Your examples show how to list, and read from alternative streams, but not how to create them. Does this library support the functionality to create the streams as well ? And if so, then how? @RichardD2

**Comment by RichardD2** [comment]
It's just a case of passing the right `FileMode` option to the `GetAlternateDataStream` method. The overload without that parameter uses `FileMode.OpenOrCreate` by default.

You can specify any of [the `FileMode` values](https://docs.microsoft.com/en-gb/dotnet/api/system.io.filemode) except `Truncate` or `Append`. _(This should probably be its own `Enum`, but I wanted to keep it as close as possible to the existing file API.)_

Using a `FileSystemInfo`:

```
AlternateDataStreamInfo ads = file.GetAlternateDataStream(streamName, FileMode.OpenOrCreate);
using (FileStream stream = ads.OpenWrite())
{
    // Write to the stream here...
}
```

Using a file path:

```
AlternateDataStreamInfo ads = FileSystem.GetAlternateDataStream(filePath, streamName, FileMode.OpenOrCreate);
using (FileStream stream = ads.OpenWrite())
{
    // Write to the stream here...
}
```

Once you have an `AlternateDataStream` instance, it also provides `OpenRead` and `OpenText` methods, along with overloads of the `Open` method which let you specify the `FileMode`, `FileAccess`, `FileShare`, buffer size, and async IO flag.
