### ISSUE TITLE
Read Only Attribute on NTFS Stream

### ISSUE THREAD

**Issue by peterkozak** [RichardD2/NTFS-Streams#7]
<img width="543" alt="Capture" src="https://user-images.githubusercontent.com/26090981/60883101-8fc6e600-a249-11e9-9b9b-09ffe6b4f8c3.PNG">
Hi,

i'm trying to change the content of an NTFS Stream on a Folder (not a file).
It works like a charm, except for some streams which have the "Read Only" attribute set.
Is there any way to change the attributes using your library?

Thanks,
Peter

**Comment by RichardD2** [comment]
Everything I've read suggests that the alternate streams don't get their own "read only" attribute - they just inherit the attribute from the main file. In which case, the standard [File.SetAttributes](https://docs.microsoft.com/en-gb/dotnet/api/system.io.file.setattributes) method should work.

[The NirSoft AlternateStreamView tool](https://www.nirsoft.net/utils/alternate_data_streams.html) shows the attributes of the file against the stream, which may be what's causing the confusion.

Let me know if you're using a different tool, or if you've found any documentation suggesting an ADS can have different attributes than the main file.
